import { puzzles as en } from "../en/puzzles";

/* eslint-disable no-useless-computed-key */
export const puzzles: typeof en = {
  ["square"]: "vierkant",
  ["circle"]: "cirkel",
  ["triangle"]: "driehoek",
  ["heart"]: "hart",
  ["spade"]: "schop",
  ["rocket"]: "raket",
  ["fish"]: "vis",
  ["petal-light-blue"]: "lichtblauw bloemblad",
  ["flower-center"]: "centrum bloem",
  ["sclera"]: "oogwit",
  ["pupil"]: "pupil",
  ["sad-mouth"]: "treurige mond",
  ["happy-mouth"]: "vrolijke mond",
  ["wink-eyes-right"]: "knipoog rechts",
  ["wink-eyes-left"]: "knipoog links",
  ["yellow-disc"]: "gele schijf",
  ["fish-only-eye"]: "vissenoog",
  ["fish-no-eye"]: "vis zonder oog",
  ["sun"]: "zon",
  ["sky"]: "hemel",
  ["grass"]: "gras",
  ["disc"]: "schijf",
  ["disc-moved-left"]: "schijf, links verschoven",
  ["disc-moved-right"]: "schijf, rechts verschoven",
  ["hole"]: "gat",
  ["door"]: "deur",
  ["padlock"]: "hangslot",
  ["eyes"]: "ogen",
  ["face"]: "gezicht",
  ["body"]: "lichaam",
  ["top flap"]: "sluitflap",
  ["bottom flap"]: "onderste flap",
  ["mouth"]: "mond",
  ["ball"]: "bal",
  ["mane"]: "manen",
  ["hair"]: "haar",
  ["cloud"]: "wolk",
  ["wall"]: "muur"
}
