/* eslint-disable no-useless-computed-key */
export const puzzles = {
  ["square"]: "square",
  ["circle"]: "circle",
  ["triangle"]: "triangle",
  ["heart"]: "heart",
  ["spade"]: "spade",
  ["rocket"]: "rocket",
  ["fish"]: "fish",
  ["petal-light-blue"]: "light blue petal",
  ["flower-center"]: "center of flower",
  ["sclera"]: "eye sclera",
  ["pupil"]: "eye pupil",
  ["sad-mouth"]: "sad mouth",
  ["happy-mouth"]: "happy mouth",
  ["wink-eyes-right"]: "wink eyes right",
  ["wink-eyes-left"]: "wink eyes left",
  ["yellow-disc"]: "yellow disc",
  ["fish-only-eye"]: "fish eye",
  ["fish-no-eye"]: "blind fish",
  ["sun"]: "sun",
  ["sky"]: "sky",
  ["grass"]: "grass",
  ["disc"]: "disc",
  ["disc-moved-left"]: "disc moved left",
  ["disc-moved-right"]: "disc moved right",
  ["hole"]: "hole",
  ["door"]: "door",
  ["padlock"]: "padlock",
  ["eyes"]: "eyes",
  ["face"]: "face",
  ["body"]: "body",
  ["top flap"]: "top flap",
  ["bottom flap"]: "bottom flap",
  ["mouth"]: "mouth",
  ["ball"]: "ball",
  ["mane"]: "mane",
  ["hair"]: "hair",
  ["cloud"]: "cloud",
  ["wall"]: "wall"
}
